[package]
name = "kittyfb"
version = "0.1.0"
authors = ["Kamil Koczurek <koczurekk@gmail.com>"]
edition = "2018"
description = "renders pictures to a kitty terminal"
license = "MIT"

[dependencies]
base64 = "0.12"
libc = "0.2"
rand = "0.7"
